[toolchain]
anchor_version = "0.31.1"


[features]
resolution = true
skip-lint = false


[programs.devnet]
de_party = "ParTyJHHCxDHCZkeXBZTAtMQT1t1eospvjgYdpYQmHb"

[programs.localnet]
de_party = "ParTyJHHCxDHCZkeXBZTAtMQT1t1eospvjgYdpYQmHb"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "NODE_OPTIONS='--no-deprecation' yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh"
program = "tests/fixtures/dlp.so"
upgradeable = false
